name: Auto assign issue

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-24.04
    steps:
      - run: gh issue edit ${{ github.event.issue.number }} --add-assignee DuffmanCC -R ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
